  # publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position controllers
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: chassis_link__front_right_steer
    pid: {p: 100.0, i: 1, d: 1.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: chassis_link__front_left_steer
    pid: {p: 100.0, i: 1, d: 1.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_right_steer__front_right_wheel
    pid: {p: 100.0, i: 1, d: 1.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_left_steer__front_left_wheel
    pid: {p: 100.0, i: 1, d: 1.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: rear_right_steer__rear_right_wheel
    pid: {p: 100.0, i: 1, d: 1.0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: rear_left_steer__rear_left_wheel
    pid: {p: 100.0, i: 1, d: 1.0}
